# file generated by setuptools_scm
# don't change, don't track in version control
__version__ = version = '0.1.dev888+g03f2124.d20230903'
__version_tuple__ = version_tuple = (0, 1, 'dev888', 'g03f2124.d20230903')
